api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "gso-configurator-cart-transform"
type = "function"
uid = "6f7b2101-b341-a084-e4ac-4bb1412790ea90097e81"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
