import {
  Page,
  Layout,
  Card,
  Text,
  Button,
  BlockStack,
  InlineStack,
  Badge,
  Divider,
  TextField,
  Checkbox,
} from "@shopify/polaris";
import { Form, useActionData, useLoaderData, useNavigation, useNavigate } from "react-router";
import { authenticate } from "../shopify.server";
import db from "../db.server";
import { buildBrandRates, computeEntryCosts, machineRatePerHour, type BrandInkRates } from "../lib/rip-actual-costs.server";
import { PRINT_LOG_USAGE_SOURCE } from "../lib/print-log-writeback-shared";
import {
  WRITEBACK_PHRASE,
  computePrintLogWriteback,
  parseWritebackProvenance,
} from "../lib/print-log-writeback.server";
import { resolvePrintDuration } from "../lib/rip-duration.server";
import crypto from "node:crypto";

const productionStatuses = [
  { label: "New", value: "new" },
  { label: "Prepress", value: "prepress" },
  { label: "Proof Needed", value: "proof_needed" },
  { label: "Proof Sent", value: "proof_sent" },
  { label: "Proof Approved", value: "proof_approved" },
  { label: "Ready to Print", value: "ready_to_print" },
  { label: "Printing", value: "printing" },
  { label: "Cutting", value: "cutting" },
  { label: "Laminating", value: "laminating" },
  { label: "QC", value: "qc" },
  { label: "Packing", value: "packing" },
  { label: "Ready for Pickup", value: "ready_for_pickup" },
  { label: "Shipped", value: "shipped" },
  { label: "Completed", value: "completed" },
  { label: "On Hold", value: "on_hold" },
  { label: "Reprint Needed", value: "reprint_needed" },
  { label: "Cancelled", value: "cancelled" },
];

const priorityOptions = [
  { label: "Low", value: "low" },
  { label: "Normal", value: "normal" },
  { label: "Rush", value: "rush" },
  { label: "Critical", value: "critical" },
];

const fileTypeOptions = [
  { label: "Artwork", value: "artwork" },
  { label: "Proof", value: "proof" },
  { label: "Dieline", value: "dieline" },
  { label: "Customer PDF", value: "customer_pdf" },
  { label: "Print File", value: "print_file" },
  { label: "Product Image", value: "image" },
  { label: "Other", value: "other" },
];

const assetSourceOptions = [
  { label: "Manual link", value: "manual" },
  { label: "Google Drive", value: "google_drive" },
  { label: "Shopify / customer upload", value: "shopify" },
  { label: "Zakeke", value: "zakeke" },
  { label: "Email attachment", value: "email" },
  { label: "NAS / local storage", value: "nas" },
  { label: "VersaWorks", value: "versaworks" },
  { label: "RasterLink", value: "rasterlink" },
  { label: "Generated by GSO ERP", value: "generated" },
];

const defaultChecklist = [
  { section: "prepress", label: "Artwork received / linked", sortOrder: 10 },
  { section: "prepress", label: "Dieline / size confirmed", sortOrder: 20 },
  { section: "prepress", label: "Proof sent if required", sortOrder: 30 },
  { section: "prepress", label: "Proof approved", sortOrder: 40 },
  { section: "production", label: "Material pulled", sortOrder: 50 },
  { section: "production", label: "Machine assigned", sortOrder: 60 },
  { section: "production", label: "Print complete", sortOrder: 70 },
  { section: "production", label: "Cut / laminate / finish complete", sortOrder: 80 },
  { section: "qc", label: "QC passed", sortOrder: 90 },
  { section: "packing", label: "Packed and labeled", sortOrder: 100 },
];

function labelForStatus(value: string) {
  return productionStatuses.find((status) => status.value === value)?.label || value;
}

function money(value: any) {
  return (Number(value) || 0).toFixed(2);
}

// 13A.7B: the legacy hardcoded ink rates (Roland 156.99/750, Mimaki 190/1000)
// and the $5 recovery constant are REMOVED. Ink cost comes from the shared
// verified channel-cost engine (same as Audit Actual Costs / 13A.7A) and the
// machine rate from the ONE configurable source machineRatePerHour() ($8/hr).
function summarizeActualPrintLogs(job: any, entries: any[], rates: BrandInkRates[], ratePerHour: number) {
  const revenue = (job.items || []).reduce((sum: number, item: any) => sum + Number(item.quantity || 0) * Number(item.unitPrice || 0), 0);
  const estimatedCost = (job.items || []).reduce((sum: number, item: any) => sum + Number(item.quantity || 0) * Number(item.unitCost || 0), 0);
  // Cut rows are separate operations: never ink/time-costed.
  const printEntries = entries.filter((entry: any) => !String(entry.status || "").toLowerCase().startsWith("cut:"));
  const actualSqft = printEntries.reduce((sum, entry) => sum + Number(entry.sqft || 0), 0);
  const actualInkMl = printEntries.reduce((sum, entry) => sum + Number(entry.inkMl || 0), 0);
  const cmykInkMl = printEntries.reduce((sum, entry) => sum + Number(entry.cmykInkMl || 0), 0);
  const whiteInkMl = printEntries.reduce((sum, entry) => sum + Number(entry.whiteInkMl || 0), 0);
  const glossInkMl = printEntries.reduce((sum, entry) => sum + Number(entry.glossInkMl || 0), 0);
  // 13A.7C: reliable per-row duration (derived print stamps > stored > 0).
  const actualPrintMinutes = printEntries.reduce((sum, entry) => sum + resolvePrintDuration(entry).minutes, 0);
  let actualInkCost = 0;
  let inkRatesCovered = true;
  for (const entry of printEntries) {
    const costs = computeEntryCosts(entry, rates);
    if (costs.inkCost != null) actualInkCost += costs.inkCost;
    else if (Number(entry.inkMl) > 0) inkRatesCovered = false;
  }
  const actualMachineCost = (actualPrintMinutes / 60) * ratePerHour;
  const roughActualPrintCost = actualInkCost + actualMachineCost;
  const estimatedProfit = revenue - estimatedCost;
  return {
    entryCount: entries.length,
    cutRowCount: entries.length - printEntries.length,
    actualSqft,
    actualInkMl,
    cmykInkMl,
    whiteInkMl,
    glossInkMl,
    actualPrintMinutes,
    actualInkCost,
    inkRatesCovered,
    actualMachineCost,
    machineRatePerHour: ratePerHour,
    roughActualPrintCost,
    revenue,
    estimatedCost,
    estimatedProfit,
    conservativeProfitAfterLoggedPrintCost: revenue - estimatedCost - roughActualPrintCost,
    lastLogAt: entries[0]?.createdAt || null,
  };
}


function summarizeMaterialUsage(usages: any[]) {
  // 13A.7B split: rows imported by the print-log writeback (source
  // "print_log") are PRINT cost, not media/material cost — separating them
  // prevents double counting in the final-cost formula.
  const manualUsages = usages.filter((usage: any) => String(usage.source || "") !== PRINT_LOG_USAGE_SOURCE);
  const printLogUsages = usages.filter((usage: any) => String(usage.source || "") === PRINT_LOG_USAGE_SOURCE);
  const materialCost = manualUsages.reduce((sum, usage) => sum + Number(usage.totalCost || 0), 0);
  const printLogRecordedCost = printLogUsages.reduce((sum, usage) => sum + Number(usage.totalCost || 0), 0);
  const pulledQty = manualUsages.reduce((sum, usage) => sum + Number(usage.pulledQty || 0), 0);
  const usedQty = manualUsages.reduce((sum, usage) => sum + Number(usage.usedQty || 0), 0);
  const wasteQty = manualUsages.reduce((sum, usage) => sum + Number(usage.wasteQty || 0), 0);
  const reprintQty = manualUsages.reduce((sum, usage) => sum + Number(usage.reprintQty || 0), 0);
  const deductedQty = manualUsages.reduce((sum, usage) => sum + Number(usage.stockDeductedQty || 0), 0);
  const wastePct = usedQty > 0 ? (wasteQty / usedQty) * 100 : 0;
  return { materialCost, printLogRecordedCost, printLogUsageCount: printLogUsages.length, pulledQty, usedQty, wasteQty, reprintQty, deductedQty, wastePct };
}

function summarizeFinalActualCosts(job: any, actuals: any, materialSummary: any) {
  const revenue = (job.items || []).reduce((sum: number, item: any) => sum + Number(item.quantity || 0) * Number(item.unitPrice || 0), 0);
  const estimatedCost = (job.items || []).reduce((sum: number, item: any) => sum + Number(item.quantity || 0) * Number(item.unitCost || 0), 0);
  // Recorded print-log actuals (owner-gated writeback) win over the live
  // preview; the live number remains a preview until applied.
  const printLogRecorded = Number(materialSummary?.printLogRecordedCost || 0);
  const printCost = printLogRecorded > 0 ? printLogRecorded : Number(actuals?.roughActualPrintCost || 0);
  const printCostSource = printLogRecorded > 0 ? "recorded_print_log" : "live_preview";
  const materialCost = Number(materialSummary?.materialCost || 0);
  const laborCost = Number(job.actualLaborCost || 0);
  const packingCost = Number(job.actualPackingCost || 0);
  const shippingCost = Number(job.actualShippingCost || 0);
  const outsourceCost = Number(job.actualOutsourceCost || 0);
  const otherCost = Number(job.actualOtherCost || 0);
  const reprintCost = Number(job.actualReprintCost || 0);
  const liveActualTotal = printCost + materialCost + laborCost + packingCost + shippingCost + outsourceCost + otherCost + reprintCost;
  const finalTotal = Number(job.actualTotalCost || 0) || liveActualTotal;
  const finalProfit = revenue - finalTotal;
  const finalMargin = revenue > 0 ? (finalProfit / revenue) * 100 : 0;
  const estimateVariance = finalTotal - estimatedCost;
  return { revenue, estimatedCost, printCost, printCostSource, materialCost, laborCost, packingCost, shippingCost, outsourceCost, otherCost, reprintCost, liveActualTotal, finalTotal, finalProfit, finalMargin, estimateVariance };
}

function materialStockTone(material: any) {
  if (material?.stockOnHand == null || material?.reorderPoint == null) return undefined;
  return Number(material.stockOnHand) <= Number(material.reorderPoint) ? "critical" : "success";
}

function materialStockLabel(material: any) {
  if (!material) return "No database material";
  const stock = material.stockOnHand == null ? "not set" : `${Number(material.stockOnHand).toFixed(2)} ${material.baseUnit || material.unit || "units"}`;
  const reorder = material.reorderPoint == null ? "not set" : `${Number(material.reorderPoint).toFixed(2)}`;
  return `Stock: ${stock} | Reorder point: ${reorder}`;
}

function materialTypeLabel(value: string) {
  const labels: Record<string, string> = {
    roll_media: "Roll media",
    laminate: "Laminate",
    ink: "Ink",
    packaging: "Packaging",
    labor: "Labor",
    outsourced: "Outsourced",
    other: "Other",
  };
  return labels[value] || value || "Material";
}

function materialOptions(materials: any[]) {
  return [
    { label: "Manual material / not in database", value: "" },
    ...materials.map((material) => ({
      label: `${material.name} (${material.unit || material.baseUnit || "unit"}) - $${money(material.calculatedUnitCost || material.costPerUnit || 0)}`,
      value: material.id,
    })),
  ];
}

function safeDateInput(value: any) {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  return date.toISOString().slice(0, 10);
}

function slugPart(value: any, fallback = "JOB") {
  const clean = String(value || fallback)
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 30);
  return clean || fallback;
}

function dateStamp(value = new Date()) {
  return value.toISOString().slice(0, 10).replace(/-/g, "");
}

async function buildNextJobTicket(shop: string, now = new Date()) {
  const stamp = dateStamp(now);
  const start = new Date(now);
  start.setHours(0, 0, 0, 0);
  const end = new Date(start);
  end.setDate(end.getDate() + 1);

  const countToday = await db.productionJob.count({
    where: { shop, createdAt: { gte: start, lt: end } },
  });

  for (let sequence = countToday + 1; sequence < countToday + 5000; sequence += 1) {
    const ticket = `GSO-${stamp}-${String(sequence).padStart(4, "0")}`;
    const existing = await db.productionJob.findFirst({ where: { shop, jobTicket: ticket } });
    if (!existing) return ticket;
  }

  return `GSO-${stamp}-${String(Date.now()).slice(-6)}`;
}

function normalizeFilePart(value: any, fallback = "ITEM") {
  return slugPart(value || fallback, fallback).slice(0, 40);
}

function itemTicketFor(jobTicket: string, index: number) {
  return `${jobTicket}-${String(index + 1).padStart(2, "0")}`;
}

function ripNameForItem(jobTicket: string, index: number) {
  return itemTicketFor(jobTicket, index);
}

function suggestedFileNameForItem(jobTicket: string, item: any, index: number) {
  const ticket = itemTicketFor(jobTicket, index);
  const product = normalizeFilePart(item.productName || item.productTitle || "PRODUCT");
  const variant = normalizeFilePart(item.variant || item.variantTitle || "VARIANT");
  const qty = Number(item.quantity || 1);
  return `${ticket}_${product}_${variant}_QTY${qty}`;
}

function folderNameForJob(job: any) {
  const ticket = job.jobTicket || `GSO-${String(job.id || "JOB").slice(-8).toUpperCase()}`;
  const customer = slugPart(job.company || job.customerName || "CUSTOMER");
  const firstProduct = slugPart(job.items?.[0]?.productTitle || "JOB");
  return `${ticket} - ${customer} - ${firstProduct}`;
}

function copyText(value: any) {
  if (typeof navigator !== "undefined" && navigator.clipboard && value) {
    navigator.clipboard.writeText(String(value));
  }
}

function sourceLabel(value: string) {
  return assetSourceOptions.find((option) => option.value === value)?.label || value || "Manual link";
}

function isImageUrl(url: any) {
  const value = String(url || "").split("?")[0].toLowerCase();
  return /\.(png|jpg|jpeg|gif|webp|svg)$/i.test(value);
}

function isPdfUrl(url: any) {
  const value = String(url || "").split("?")[0].toLowerCase();
  return value.endsWith(".pdf");
}

function assetRoleLabel(role: string) {
  if (role === "productImage") return "Product image";
  if (role === "artwork") return "Main artwork";
  if (role === "proof") return "Current proof";
  if (role === "printFile") return "Print file";
  return "Reference file";
}

function jobAssetUpdateForRole(role: string, fileUrl: string) {
  if (role === "productImage") return { productImageUrl: fileUrl };
  if (role === "artwork") return { artworkUrl: fileUrl };
  if (role === "proof") return { proofUrl: fileUrl };
  if (role === "printFile") return { printFileUrl: fileUrl };
  return {};
}

function roleFromFileType(fileType: string) {
  if (fileType === "image") return "productImage";
  if (fileType === "artwork" || fileType === "customer_pdf") return "artwork";
  if (fileType === "proof") return "proof";
  if (fileType === "print_file") return "printFile";
  return "reference";
}

function parseJson(value: any) {
  if (!value) return null;
  try {
    return typeof value === "string" ? JSON.parse(value) : value;
  } catch (_error) {
    return null;
  }
}

function configFromItem(item: any) {
  const selected = parseJson(item.selectedAddOns) || {};
  const materialSummary = String(item.materialSummary || item.productionNotes || "");
  const variantParts = String(item.variantTitle || "")
    .split("/")
    .map((part) => part.trim())
    .filter(Boolean);
  const productType = String(selected.productType || "");
  const productFamily = String(selected.productFamily || "");
  const isJar =
    productFamily.toLowerCase() === "jars" ||
    productType.startsWith("jar_") ||
    String(item.sku || "").toUpperCase().startsWith("JAR-") ||
    /Product Family:\s*Jars/i.test(materialSummary);

  const summaryValue = (label: string) => {
    const match = materialSummary.match(new RegExp(`${label}:\\s*([^|\\n]+)`, "i"));
    return match?.[1]?.trim() || "";
  };

  return {
    isJar,
    productFamily,
    productType,
    material: selected.material || variantParts[0] || "",
    finish: selected.finish || variantParts[1] || "",
    productionFinish: selected.productionFinish || item.selectedFinish || "",
    bagColor: selected.bagColor || variantParts[2] || "",
    sides: selected.sides || "",
    jarColor: selected.jarColor || summaryValue("Jar Color") || "",
    labelSet: selected.labelSet || summaryValue("Label Set") || "",
  };
}

function lineTotalForItem(item: any) {
  return Number(item.quantity || 0) * Number(item.unitPrice || 0);
}

function firstImageFromQuoteItem(item: any) {
  const costSnapshot = parseJson(item.costSnapshot);
  const priceSnapshot = parseJson(item.priceSnapshot);
  return (
    item.productImageUrl ||
    costSnapshot?.productImageUrl ||
    costSnapshot?.imageUrl ||
    priceSnapshot?.productImageUrl ||
    priceSnapshot?.imageUrl ||
    ""
  );
}

function snapshotValue(item: any, key: string) {
  return item?.[key] || parseJson(item.costSnapshot)?.[key] || parseJson(item.priceSnapshot)?.[key] || "";
}

async function createEvent(shop: string, jobId: string, eventType: string, message: string, data?: { oldValue?: string; newValue?: string; createdBy?: string }) {
  return db.productionJobEvent.create({
    data: {
      shop,
      jobId,
      eventType,
      message,
      oldValue: data?.oldValue || null,
      newValue: data?.newValue || null,
      createdBy: data?.createdBy || null,
    },
  });
}

function publicBaseUrl(request: Request) {
  const envUrl = process.env.SHOPIFY_APP_URL || process.env.APP_URL || process.env.HOST || "";
  if (envUrl.startsWith("http://") || envUrl.startsWith("https://")) return envUrl.replace(/\/$/, "");
  if (envUrl) return `https://${envUrl.replace(/\/$/, "")}`;
  return new URL(request.url).origin;
}

async function ensureProofApprovalToken(shop: string, jobId: string) {
  const job = await db.productionJob.findFirst({ where: { shop, id: jobId } });
  if (!job) throw new Error("Production job not found.");
  if (job.proofApprovalToken) return job.proofApprovalToken;
  const token = `gso_${crypto.randomBytes(24).toString("hex")}`;
  await db.productionJob.update({
    where: { id: job.id },
    data: {
      proofApprovalToken: token,
      proofStatus: job.proofStatus === "approved" ? job.proofStatus : "sent",
      proofSentAt: job.proofSentAt || new Date(),
    },
  });
  await createEvent(shop, job.id, "proof_portal_created", "Customer proof approval link created.");
  return token;
}

async function sendProductionAlert(job: any) {
  const webhookUrl = process.env.SLACK_WEBHOOK_URL || process.env.PRODUCTION_SLACK_WEBHOOK_URL;
  if (!webhookUrl) return { sent: false, reason: "No Slack webhook configured." };

  const text = [
    "🚨 New GSO Production Job",
    `Customer: ${job.company || job.customerName || "Unknown"}`,
    `Job: ${job.jobTicket || job.id}`,
    `Quote: ${job.quoteId || "N/A"}`,
    `Priority: ${job.priority}`,
    `Status: ${labelForStatus(job.status)}`,
  ].join("\n");

  try {
    const response = await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text }),
    });
    return { sent: response.ok, reason: response.ok ? "Slack alert sent." : `Slack returned ${response.status}` };
  } catch (error: any) {
    return { sent: false, reason: error?.message || "Slack alert failed." };
  }
}

async function createProductionJobFromQuote(shop: string, quoteId: string) {
  const existingJob = await db.productionJob.findFirst({ where: { shop, quoteId } });
  if (existingJob) return { job: existingJob, created: false };

  const quote = await db.quote.findFirst({
    where: { shop, id: quoteId },
    include: { items: true },
  });

  if (!quote) throw new Error("Quote not found.");
  if (!["paid", "production"].includes(quote.status)) {
    throw new Error(
      quote.status === "deposit_paid"
        ? "Balance must be paid before production can start."
        : "Production can start only after the quote is fully paid.",
    );
  }
  if (!quote.items.length) throw new Error("Quote has no items to send to production.");

  const jobTicket = await buildNextJobTicket(shop);

  const job = await db.productionJob.create({
    data: {
      shop,
      quoteId: quote.id,
      quoteNumber: quote.id,
      jobTicket,
      assetInboxKey: jobTicket,
      customerName: quote.customerName || null,
      company: quote.company || null,
      email: quote.email || null,
      phone: quote.phone || null,
      status: "new",
      priority: "normal",
      customerNotes: quote.notes || null,
      internalNotes: "Created from quote.",
      productImageUrl: firstImageFromQuoteItem(quote.items[0]),
      proofUrl: null,
      items: {
        create: quote.items.map((item: any, index: number) => ({
          shop,
          quoteItemId: item.id,
          itemTicket: itemTicketFor(jobTicket, index),
          ripJobName: ripNameForItem(jobTicket, index),
          suggestedFileName: suggestedFileNameForItem(jobTicket, item, index),
          productTitle: item.productName || "Custom item",
          variantTitle: item.variant || null,
          sku: item.sku || null,
          quantity: Number(item.quantity) || 1,
          unitPrice: Number(item.unitPrice) || 0,
          unitCost: Number(item.unitCost) || 0,
          productImageUrl: firstImageFromQuoteItem(item) || null,
          shopifyProductGid: snapshotValue(item, "shopifyProductGid") || snapshotValue(item, "shopifyProductId") || null,
          shopifyVariantGid: snapshotValue(item, "shopifyVariantGid") || snapshotValue(item, "shopifyVariantId") || null,
          recipeId: item.recipeId || snapshotValue(item, "recipeId") || null,
          recipeName: item.recipeName || snapshotValue(item, "recipeName") || null,
          selectedFinish: item.selectedFinish || snapshotValue(item, "selectedFinish") || null,
          selectedAddOns: item.selectedAddOnIds || snapshotValue(item, "selectedAddOns") || null,
          costSnapshot: item.costSnapshot || null,
          priceSnapshot: item.priceSnapshot || null,
          productionNotes: item.notes || null,
          sortOrder: index + 1,
        })),
      },
      checklistItems: {
        create: defaultChecklist.map((check) => ({ shop, ...check })),
      },
      events: {
        create: [
          {
            shop,
            eventType: "created_from_quote",
            message: `Production job ${jobTicket} created from quote ${quote.id}.`,
          },
        ],
      },
    },
    include: { items: true, events: true },
  });

  await db.quote.updateMany({
    where: { shop, id: quote.id, status: { not: "paid" } },
    data: { status: "production" },
  });

  const proofUrl = `/app/erp/production/${job.id}/proof`;
  await db.productionJob.update({
    where: { id: job.id },
    data: { proofUrl },
  });
  await db.productionJobFile.create({
    data: {
      shop,
      jobId: job.id,
      fileName: "Standard GSO Proof Sheet",
      fileType: "proof",
      fileUrl: proofUrl,
      assetRole: "proof",
      assetSource: "generated",
      sourceRef: jobTicket,
      matchedBy: "auto_created_from_job",
      jobTicket,
      originalFileName: "Standard GSO Proof Sheet",
      notes: "Auto-created internal proof sheet. Open to edit images/artwork and print/export.",
    },
  });
  await createEvent(shop, job.id, "proof_created", "Standard GSO proof sheet auto-created.");

  const alertResult = await sendProductionAlert(job);
  await createEvent(
    shop,
    job.id,
    alertResult.sent ? "alert_sent" : "alert_skipped",
    alertResult.reason || "Production alert processed."
  );

  await db.productionJob.update({
    where: { id: job.id },
    data: { alertSentAt: alertResult.sent ? new Date() : null },
  });

  return { job, created: true };
}

export async function loader({ request }: { request: Request }) {
  const { session } = await authenticate.admin(request);
  const shop = session.shop;
  const baseUrl = publicBaseUrl(request);

  const [jobs, quotes] = await Promise.all([
    db.productionJob.findMany({
      where: { shop, active: true },
      orderBy: [{ updatedAt: "desc" }],
      include: {
        items: { orderBy: { sortOrder: "asc" } },
        files: { orderBy: { createdAt: "desc" } },
        events: { orderBy: { createdAt: "desc" }, take: 20 },
        checklistItems: { orderBy: [{ section: "asc" }, { sortOrder: "asc" }] },
        materialUsages: { orderBy: { createdAt: "desc" } },
        inventoryMovements: { orderBy: { createdAt: "desc" }, take: 20 },
      },
    }),
    db.quote.findMany({
      where: { shop, status: { in: ["approved", "paid", "production"] } },
      orderBy: { updatedAt: "desc" },
      include: { items: true },
    }),
  ]);

  const jobIds = jobs.map((job: any) => job.id);
  const [printLogEntries, machines] = await Promise.all([
    jobIds.length
      ? db.printLogEntry.findMany({
          where: { shop, productionJobId: { in: jobIds } },
          orderBy: { createdAt: "desc" },
        })
      : Promise.resolve([]),
    db.machine.findMany({
      where: { shop, active: true },
      select: { name: true, inkChannels: { select: { inkType: true, inkName: true, enabled: true, costPerMl: true, cartridgeCost: true, cartridgeMl: true } } },
      take: 50,
    }),
  ]);
  const rates = buildBrandRates(machines);
  const ratePerHour = machineRatePerHour();

  const entriesByJob = printLogEntries.reduce((map: Record<string, any[]>, entry: any) => {
    if (!entry.productionJobId) return map;
    map[entry.productionJobId] = map[entry.productionJobId] || [];
    map[entry.productionJobId].push(entry);
    return map;
  }, {});

  const jobsWithActuals = jobs.map((job: any) => {
    const jobEntries = entriesByJob[job.id] || [];
    // 13A.7B: server-computed writeback preview (the apply action re-computes
    // fresh — client numbers are never trusted) + digest of already-applied
    // print_log usage rows for the UI.
    const writeback = computePrintLogWriteback({
      job: { id: job.id, jobTicket: job.jobTicket, items: job.items || [], actualCostFinalized: Boolean(job.actualCostFinalized) },
      entries: jobEntries,
      rates,
      machineRatePerHour: ratePerHour,
    });
    const appliedRows = (job.materialUsages || []).filter((usage: any) => String(usage.source || "") === PRINT_LOG_USAGE_SOURCE);
    const appliedProvenance = appliedRows.length ? parseWritebackProvenance(appliedRows[0].notes).provenance : null;
    return {
      ...job,
      actuals: summarizeActualPrintLogs(job, jobEntries, rates, ratePerHour),
      writebackPreview: writeback,
      printLogApplied: appliedRows.length
        ? {
            totalCost: appliedRows.reduce((sum: number, usage: any) => sum + Number(usage.totalCost || 0), 0),
            components: appliedRows.map((usage: any) => ({ name: usage.materialName, totalCost: Number(usage.totalCost || 0), unit: usage.unit, usedQty: Number(usage.usedQty || 0) })),
            appliedAt: (appliedProvenance?.appliedAt as string) || null,
            appliedBy: (appliedProvenance?.appliedBy as string) || null,
          }
        : null,
      customerProofUrl: job.proofApprovalToken ? `${baseUrl}/proof/${job.proofApprovalToken}` : "",
    };
  });


  const materials = await db.material.findMany({
    where: { shop, active: true },
    orderBy: [{ materialType: "asc" }, { name: "asc" }],
  });

  return Response.json({ jobs: jobsWithActuals, quotes, materials });
}

export async function action({ request }: { request: Request }) {
  const { session } = await authenticate.admin(request);
  const shop = session.shop;
  const formData = await request.formData();
  const intent = String(formData.get("intent") || "");

  if (intent === "createFromQuote") {
    const quoteId = String(formData.get("quoteId") || "");
    try {
      const result = await createProductionJobFromQuote(shop, quoteId);
      return Response.json({ ok: true, message: result.created ? "Production job created." : "Production job already exists.", jobId: result.job.id });
    } catch (error: any) {
      return Response.json({ ok: false, message: error?.message || "Could not create production job." });
    }
  }

  if (intent === "backfillTickets") {
    const jobs = await db.productionJob.findMany({
      where: { shop, active: true },
      orderBy: { createdAt: "asc" },
      include: { items: { orderBy: { sortOrder: "asc" } } },
    });

    let updatedJobs = 0;
    let updatedItems = 0;

    for (const job of jobs) {
      let jobTicket = job.jobTicket;
      if (!jobTicket) {
        jobTicket = await buildNextJobTicket(shop, new Date(job.createdAt || Date.now()));
        await db.productionJob.update({
          where: { id: job.id },
          data: {
            jobTicket,
            assetInboxKey: job.assetInboxKey || jobTicket,
          },
        });
        await createEvent(shop, job.id, "job_ticket_backfilled", `Job ticket assigned: ${jobTicket}.`);
        updatedJobs += 1;
      }

      for (let index = 0; index < (job.items || []).length; index += 1) {
        const item = job.items[index];
        if (!item.itemTicket || !item.ripJobName || !item.suggestedFileName) {
          const itemTicket = itemTicketFor(jobTicket, index);
          await db.productionJobItem.update({
            where: { id: item.id },
            data: {
              itemTicket,
              ripJobName: item.ripJobName || itemTicket,
              suggestedFileName: item.suggestedFileName || suggestedFileNameForItem(jobTicket, item, index),
            },
          });
          updatedItems += 1;
        }
      }
    }

    return Response.json({ ok: true, message: `Backfilled ${updatedJobs} job ticket(s) and ${updatedItems} item ticket(s).` });
  }

  if (intent === "changeStatus") {
    const jobId = String(formData.get("jobId") || "");
    const status = String(formData.get("status") || "new");
    const job = await db.productionJob.findFirst({ where: { shop, id: jobId } });
    if (!job) return Response.json({ ok: false, message: "Job not found." }, { status: 404 });

    await db.productionJob.update({
      where: { id: jobId },
      data: {
        status,
        completedAt: status === "completed" ? new Date() : job.completedAt,
      },
    });
    await createEvent(shop, jobId, "status_change", `Status changed from ${labelForStatus(job.status)} to ${labelForStatus(status)}.`, {
      oldValue: job.status,
      newValue: status,
    });
    return Response.json({ ok: true, message: "Status updated." });
  }

  if (intent === "updateJob") {
    const jobId = String(formData.get("jobId") || "");
    const dueDate = String(formData.get("dueDate") || "");
    await db.productionJob.updateMany({
      where: { shop, id: jobId },
      data: {
        priority: String(formData.get("priority") || "normal"),
        assignedTo: String(formData.get("assignedTo") || "") || null,
        dueDate: dueDate ? new Date(`${dueDate}T12:00:00`) : null,
        internalNotes: String(formData.get("internalNotes") || "") || null,
        customerNotes: String(formData.get("customerNotes") || "") || null,
        artworkUrl: String(formData.get("artworkUrl") || "") || null,
        proofUrl: String(formData.get("proofUrl") || "") || null,
        printFileUrl: String(formData.get("printFileUrl") || "") || null,
        productImageUrl: String(formData.get("productImageUrl") || "") || null,
        assetFolderUrl: String(formData.get("assetFolderUrl") || "") || null,
        sourceFolderUrl: String(formData.get("sourceFolderUrl") || "") || null,
        assetInboxKey: String(formData.get("assetInboxKey") || "") || null,
      },
    });
    await createEvent(shop, jobId, "job_updated", "Production job details updated.");
    return Response.json({ ok: true, message: "Job updated." });
  }

  if (intent === "addFile") {
    const jobId = String(formData.get("jobId") || "");
    const fileUrl = String(formData.get("fileUrl") || "").trim();
    if (!fileUrl) return Response.json({ ok: false, message: "File URL is required." }, { status: 400 });
    const fileName = String(formData.get("fileName") || "") || fileUrl.split("/").pop() || "Production file";
    const fileType = String(formData.get("fileType") || "artwork");
    const assetRole = String(formData.get("assetRole") || roleFromFileType(fileType));
    const assetSource = String(formData.get("assetSource") || "manual");
    const sourceRef = String(formData.get("sourceRef") || "") || null;
    const matchedBy = String(formData.get("matchedBy") || "manual_asset_intake") || null;
    const fileNotes = String(formData.get("fileNotes") || "") || null;
    const job = await db.productionJob.findFirst({ where: { shop, id: jobId } });

    await db.productionJobFile.create({
      data: {
        shop,
        jobId,
        fileName,
        fileType,
        fileUrl,
        assetRole,
        assetSource,
        sourceRef,
        matchedBy,
        jobTicket: job?.jobTicket || null,
        originalFileName: fileName,
        notes: fileNotes ? `${fileNotes}
Asset role: ${assetRole}
Source: ${sourceLabel(assetSource)}${sourceRef ? `
Source ref: ${sourceRef}` : ""}` : `Asset role: ${assetRole}
Source: ${sourceLabel(assetSource)}${sourceRef ? `
Source ref: ${sourceRef}` : ""}`,
      },
    });

    const roleUpdate = jobAssetUpdateForRole(assetRole, fileUrl);
    if (Object.keys(roleUpdate).length) {
      await db.productionJob.updateMany({ where: { shop, id: jobId }, data: roleUpdate });
      await createEvent(shop, jobId, "asset_role_set", `${fileName} set as ${assetRoleLabel(assetRole)}.`);
    }

    await createEvent(shop, jobId, "file_added", `${fileType} file added from ${sourceLabel(assetSource)}: ${fileName}.`);
    return Response.json({ ok: true, message: "File added." });
  }

  if (intent === "setFileRole") {
    const jobId = String(formData.get("jobId") || "");
    const fileId = String(formData.get("fileId") || "");
    const assetRole = String(formData.get("assetRole") || "reference");
    const file = await db.productionJobFile.findFirst({ where: { shop, id: fileId, jobId } });
    if (!file) return Response.json({ ok: false, message: "File not found." }, { status: 404 });

    const roleUpdate = jobAssetUpdateForRole(assetRole, file.fileUrl);
    await db.productionJobFile.update({ where: { id: file.id }, data: { assetRole } });
    if (Object.keys(roleUpdate).length) {
      await db.productionJob.updateMany({ where: { shop, id: jobId }, data: roleUpdate });
      await createEvent(shop, jobId, "asset_role_set", `${file.fileName} set as ${assetRoleLabel(assetRole)}.`);
    }
    return Response.json({ ok: true, message: `${file.fileName} set as ${assetRoleLabel(assetRole)}.` });
  }

  if (intent === "deleteFile") {
    const jobId = String(formData.get("jobId") || "");
    const fileId = String(formData.get("fileId") || "");
    const file = await db.productionJobFile.findFirst({ where: { shop, id: fileId, jobId } });
    if (!file) return Response.json({ ok: false, message: "File not found." }, { status: 404 });
    await db.productionJobFile.delete({ where: { id: file.id } });
    await createEvent(shop, jobId, "file_deleted", `${file.fileType} file removed: ${file.fileName}.`);
    return Response.json({ ok: true, message: "File removed." });
  }

  if (intent === "toggleChecklist") {
    const checklistId = String(formData.get("checklistId") || "");
    const jobId = String(formData.get("jobId") || "");
    const completed = String(formData.get("completed") || "false") === "true";
    await db.productionChecklistItem.updateMany({
      where: { shop, id: checklistId, jobId },
      data: { completed, completedAt: completed ? new Date() : null },
    });
    await createEvent(shop, jobId, "checklist_updated", `Checklist item marked ${completed ? "complete" : "incomplete"}.`);
    return Response.json({ ok: true, message: "Checklist updated." });
  }


  if (intent === "addMaterialUsage") {
    const jobId = String(formData.get("jobId") || "");
    const materialId = String(formData.get("materialId") || "");
    const material = materialId ? await db.material.findFirst({ where: { shop, id: materialId } }) : null;
    const materialName = String(formData.get("materialName") || "").trim() || material?.name || "Manual material";
    const materialType = String(formData.get("materialType") || "") || material?.materialType || "other";
    const unit = String(formData.get("unit") || "") || material?.baseUnit || material?.unit || "sqft";
    const pulledQty = Number(formData.get("pulledQty") || 0);
    const usedQty = Number(formData.get("usedQty") || 0);
    const wasteQty = Number(formData.get("wasteQty") || 0);
    const reprintQty = Number(formData.get("reprintQty") || 0);
    const estimatedQty = Number(formData.get("estimatedQty") || 0);
    const costPerUnit = Number(formData.get("costPerUnit") || material?.calculatedUnitCost || material?.costPerUnit || 0);
    const billableQty = usedQty || pulledQty || estimatedQty || 0;
    const totalCost = Number(formData.get("totalCost") || 0) || (billableQty + wasteQty + reprintQty) * costPerUnit;

    const usage = await db.productionMaterialUsage.create({
      data: {
        shop,
        jobId,
        materialId: material?.id || null,
        materialName,
        materialType,
        unit,
        estimatedQty,
        pulledQty,
        usedQty,
        wasteQty,
        reprintQty,
        costPerUnit,
        totalCost,
        source: String(formData.get("source") || "manual"),
        notes: String(formData.get("materialNotes") || "") || null,
      },
    });

    const shouldDeductInventory = String(formData.get("deductInventory") || "") === "on";
    const deductionQty = Number(formData.get("deductQty") || 0) || pulledQty || (usedQty + wasteQty + reprintQty) || usedQty || 0;

    if (material && shouldDeductInventory && deductionQty > 0) {
      const beforeQty = Number(material.stockOnHand || 0);
      const afterQty = beforeQty - deductionQty;
      await db.material.update({
        where: { id: material.id },
        data: { stockOnHand: afterQty },
      });
      await db.materialInventoryMovement.create({
        data: {
          shop,
          materialId: material.id,
          jobId,
          materialUsageId: usage.id,
          movementType: "production_deduction",
          quantity: -deductionQty,
          unit,
          beforeQty,
          afterQty,
          costPerUnit,
          costImpact: deductionQty * costPerUnit,
          source: "production",
          reference: `Job ${jobId}`,
          notes: `Deducted from stock when material usage was logged for ${materialName}.`,
        },
      });
      await db.productionMaterialUsage.update({
        where: { id: usage.id },
        data: { stockDeductedQty: deductionQty, stockDeductedAt: new Date() },
      });
      await createEvent(shop, jobId, "inventory_deducted", `${deductionQty} ${unit} deducted from ${materialName}. Stock ${beforeQty.toFixed(2)} → ${afterQty.toFixed(2)}.`);
    }

    await createEvent(shop, jobId, "material_usage_added", `${materialName} added. Used ${usedQty || pulledQty || estimatedQty} ${unit}. Cost $${money(totalCost)}.`);
    return Response.json({ ok: true, message: shouldDeductInventory ? "Material usage added and inventory deducted." : "Material usage added." });
  }

  if (intent === "deleteMaterialUsage") {
    const jobId = String(formData.get("jobId") || "");
    const usageId = String(formData.get("usageId") || "");
    const usage = await db.productionMaterialUsage.findFirst({ where: { shop, id: usageId, jobId } });
    if (usage) {
      const movements = await db.materialInventoryMovement.findMany({ where: { shop, materialUsageId: usage.id } });
      for (const movement of movements) {
        const material = await db.material.findFirst({ where: { shop, id: movement.materialId } });
        if (material && Number(movement.quantity || 0) < 0) {
          const beforeQty = Number(material.stockOnHand || 0);
          const restoreQty = Math.abs(Number(movement.quantity || 0));
          const afterQty = beforeQty + restoreQty;
          await db.material.update({ where: { id: material.id }, data: { stockOnHand: afterQty } });
          await db.materialInventoryMovement.create({
            data: {
              shop,
              materialId: material.id,
              jobId,
              materialUsageId: usage.id,
              movementType: "reversal",
              quantity: restoreQty,
              unit: movement.unit,
              beforeQty,
              afterQty,
              costPerUnit: movement.costPerUnit,
              costImpact: -Number(movement.costImpact || 0),
              source: "production",
              reference: `Reversal for ${movement.id}`,
              notes: `Restored stock because material usage was removed.`,
            },
          });
          await createEvent(shop, jobId, "inventory_restored", `${restoreQty} ${movement.unit} restored to ${usage.materialName}. Stock ${beforeQty.toFixed(2)} → ${afterQty.toFixed(2)}.`);
        }
      }
      await db.productionMaterialUsage.delete({ where: { id: usage.id } });
      await createEvent(shop, jobId, "material_usage_deleted", `${usage.materialName} material usage removed.`);
    }
    return Response.json({ ok: true, message: "Material usage removed." });
  }

  if (intent === "adjustInventory") {
    const materialId = String(formData.get("materialId") || "");
    const jobId = String(formData.get("jobId") || "");
    const quantity = Number(formData.get("adjustQty") || 0);
    const notes = String(formData.get("adjustNotes") || "") || null;
    const material = await db.material.findFirst({ where: { shop, id: materialId } });
    if (!material || !quantity) return Response.json({ ok: false, message: "Choose a material and enter adjustment qty." }, { status: 400 });
    const beforeQty = Number(material.stockOnHand || 0);
    const afterQty = beforeQty + quantity;
    const unit = material.baseUnit || material.unit || "each";
    const costPerUnit = Number(material.calculatedUnitCost || material.costPerUnit || 0);
    await db.material.update({ where: { id: material.id }, data: { stockOnHand: afterQty } });
    await db.materialInventoryMovement.create({
      data: {
        shop,
        materialId: material.id,
        jobId: jobId || null,
        movementType: "adjustment",
        quantity,
        unit,
        beforeQty,
        afterQty,
        costPerUnit,
        costImpact: Math.abs(quantity) * costPerUnit,
        source: "manual",
        reference: jobId || null,
        notes,
      },
    });
    if (jobId) await createEvent(shop, jobId, "inventory_adjusted", `${material.name} adjusted by ${quantity} ${unit}. Stock ${beforeQty.toFixed(2)} → ${afterQty.toFixed(2)}.`);
    return Response.json({ ok: true, message: "Inventory adjusted." });
  }

  if (intent === "addNote") {
    const jobId = String(formData.get("jobId") || "");
    const note = String(formData.get("note") || "").trim();
    if (!note) return Response.json({ ok: false, message: "Note cannot be empty." }, { status: 400 });
    await createEvent(shop, jobId, "note", note);
    return Response.json({ ok: true, message: "Note added." });
  }

  if (intent === "createProofPortal") {
    const jobId = String(formData.get("jobId") || "");
    const token = await ensureProofApprovalToken(shop, jobId);
    return Response.json({ ok: true, message: "Customer proof link created.", token });
  }

  if (intent === "markProofSent") {
    const jobId = String(formData.get("jobId") || "");
    const token = await ensureProofApprovalToken(shop, jobId);
    await db.productionJob.updateMany({
      where: { shop, id: jobId },
      data: { proofStatus: "sent", proofSentAt: new Date(), status: "proof_sent" },
    });
    await createEvent(shop, jobId, "proof_sent", "Customer proof link marked sent.");
    return Response.json({ ok: true, message: "Proof marked sent.", token });
  }

  if (intent === "saveFinalCosts") {
    const jobId = String(formData.get("jobId") || "");
    const job = await db.productionJob.findFirst({
      where: { shop, id: jobId },
      include: { items: true, materialUsages: true },
    });
    if (!job) return Response.json({ ok: false, message: "Job not found." }, { status: 404 });

    const printLogEntries = await db.printLogEntry.findMany({
      where: { shop, productionJobId: jobId },
      orderBy: { createdAt: "desc" },
    });

    const actualLaborMinutes = Number(formData.get("actualLaborMinutes") || 0);
    const actualLaborRate = Number(formData.get("actualLaborRate") || 25);
    const typedLaborCost = Number(formData.get("actualLaborCost") || 0);
    const actualLaborCost = typedLaborCost || ((actualLaborMinutes / 60) * actualLaborRate);
    const actualPackingCost = Number(formData.get("actualPackingCost") || 0);
    const actualShippingCost = Number(formData.get("actualShippingCost") || 0);
    const actualOutsourceCost = Number(formData.get("actualOutsourceCost") || 0);
    const actualOtherCost = Number(formData.get("actualOtherCost") || 0);
    const actualReprintCost = Number(formData.get("actualReprintCost") || 0);
    const actualCostNotes = String(formData.get("actualCostNotes") || "") || null;
    const actualCostFinalized = String(formData.get("actualCostFinalized") || "false") === "true";

    const costMachines = await db.machine.findMany({
      where: { shop, active: true },
      select: { name: true, inkChannels: { select: { inkType: true, inkName: true, enabled: true, costPerMl: true, cartridgeCost: true, cartridgeMl: true } } },
      take: 50,
    });
    const actuals = summarizeActualPrintLogs(job, printLogEntries, buildBrandRates(costMachines), machineRatePerHour());
    const materialSummary = summarizeMaterialUsage(job.materialUsages || []);
    const revenue = (job.items || []).reduce((sum: number, item: any) => sum + Number(item.quantity || 0) * Number(item.unitPrice || 0), 0);
    // Recorded print-log actuals win over the live preview; manual material
    // rows are counted separately from print_log rows (no double count).
    const printCostComponent = Number(materialSummary.printLogRecordedCost || 0) > 0 ? Number(materialSummary.printLogRecordedCost) : Number(actuals.roughActualPrintCost || 0);
    const actualTotalCost = printCostComponent + Number(materialSummary.materialCost || 0) + actualLaborCost + actualPackingCost + actualShippingCost + actualOutsourceCost + actualOtherCost + actualReprintCost;
    const actualFinalProfit = revenue - actualTotalCost;
    const actualFinalMargin = revenue > 0 ? (actualFinalProfit / revenue) * 100 : 0;

    await db.productionJob.update({
      where: { id: jobId },
      data: {
        actualLaborMinutes,
        actualLaborRate,
        actualLaborCost,
        actualPackingCost,
        actualShippingCost,
        actualOutsourceCost,
        actualOtherCost,
        actualReprintCost,
        actualTotalCost,
        actualFinalProfit,
        actualFinalMargin,
        actualCostNotes,
        actualCostFinalized,
        actualCostFinalizedAt: actualCostFinalized ? new Date() : null,
        actualCostFinalizedBy: actualCostFinalized ? "GSO ERP" : null,
      },
    });

    await createEvent(shop, jobId, actualCostFinalized ? "actual_cost_finalized" : "actual_cost_updated", `Actual job cost ${actualCostFinalized ? "finalized" : "updated"}. Total cost: $${actualTotalCost.toFixed(2)}. Profit: $${actualFinalProfit.toFixed(2)}. Margin: ${actualFinalMargin.toFixed(1)}%.`);
    return Response.json({ ok: true, message: actualCostFinalized ? "Actual cost finalized." : "Actual cost updated." });
  }

  // 13A.7B: guarded print-log actual-cost writeback. Preview lives on the
  // board (loader-computed); this action RE-COMPUTES server-side, enforces the
  // typed owner phrase, and writes ink + machine-time ProductionMaterialUsage
  // rows (source "print_log") in ONE transaction. Material/media cost is
  // preview-only and never written. Manual rows and manual actual fields are
  // never touched; the job is never auto-finalized.
  if (intent === "pullPrintLogActuals") {
    const jobId = String(formData.get("jobId") || "");
    const confirmPhrase = String(formData.get("confirmPhrase") || "");
    const job = await db.productionJob.findFirst({ where: { shop, id: jobId }, include: { items: true } });
    if (!job) return Response.json({ ok: false, message: "Job not found." }, { status: 404 });
    if (confirmPhrase !== WRITEBACK_PHRASE) {
      return Response.json({ ok: false, message: `Confirmation phrase must be exactly "${WRITEBACK_PHRASE}" (case-sensitive) — nothing was written.` });
    }
    const entries = await db.printLogEntry.findMany({ where: { shop, productionJobId: jobId }, orderBy: { createdAt: "desc" } });
    const writebackMachines = await db.machine.findMany({
      where: { shop, active: true },
      select: { name: true, inkChannels: { select: { inkType: true, inkName: true, enabled: true, costPerMl: true, cartridgeCost: true, cartridgeMl: true } } },
      take: 50,
    });
    const computation = computePrintLogWriteback({
      job: { id: job.id, jobTicket: job.jobTicket, items: job.items || [], actualCostFinalized: Boolean(job.actualCostFinalized) },
      entries: entries as any,
      rates: buildBrandRates(writebackMachines),
      machineRatePerHour: machineRatePerHour(),
    });
    if (!computation.ok) {
      return Response.json({ ok: false, message: `Blocked: ${computation.blockedReason}` });
    }
    await db.$transaction([
      // Replace ONLY rows this feature owns — manual usage, inventory
      // deductions, and every other source survive untouched.
      db.productionMaterialUsage.deleteMany({ where: { shop, jobId, source: PRINT_LOG_USAGE_SOURCE } }),
      ...computation.rows.map((row) =>
        db.productionMaterialUsage.create({
          data: {
            shop,
            jobId,
            materialName: row.materialName,
            materialType: row.materialType,
            unit: row.unit,
            usedQty: row.usedQty,
            costPerUnit: row.costPerUnit,
            totalCost: row.totalCost,
            source: row.source,
            notes: row.notes,
          },
        }),
      ),
      db.productionJobEvent.create({
        data: {
          shop,
          jobId,
          eventType: "print_log_actuals_applied",
          message: `Print-log actuals imported (PARTIAL, not finalized): $${computation.totalCost.toFixed(2)} = ink ${computation.inkCost == null ? "n/a" : `$${computation.inkCost.toFixed(2)}`} + machine ${computation.machineCost == null ? "n/a" : `$${computation.machineCost.toFixed(2)} @ $${computation.machineRatePerHour}/hr`} across ${computation.printRowCount} print row(s)${computation.cutRowsExcluded ? `, ${computation.cutRowsExcluded} cut row(s) excluded` : ""}${computation.duplicatesIgnored ? `, ${computation.duplicatesIgnored} duplicate(s) ignored` : ""}. Material/media stays preview-only.`,
          newValue: computation.totalCost.toFixed(2),
          createdBy: "production-board",
        },
      }),
    ]);
    return Response.json({ ok: true, message: `Applied $${computation.totalCost.toFixed(2)} print-log actuals (ink + machine time, PARTIAL — job not finalized). Re-run any time new logs arrive; reruns replace only these imported rows.` });
  }

  if (intent === "markPrinted") {
    const jobId = String(formData.get("jobId") || "");
    await db.productionJob.updateMany({ where: { shop, id: jobId }, data: { printedAt: new Date() } });
    await createEvent(shop, jobId, "work_order_printed", "Work order marked printed.");
    return Response.json({ ok: true, message: "Work order print event tracked." });
  }

  return Response.json({ ok: false, message: "Unknown production action." }, { status: 400 });
}

function JobCard({ job, materials }: { job: any; materials: any[] }) {
  const navigate = useNavigate();
  const firstImage = job.productImageUrl || job.items?.find((item: any) => item.productImageUrl)?.productImageUrl;
  const totalRevenue = (job.items || []).reduce((sum: number, item: any) => sum + Number(item.quantity || 0) * Number(item.unitPrice || 0), 0);
  const totalCost = (job.items || []).reduce((sum: number, item: any) => sum + Number(item.quantity || 0) * Number(item.unitCost || 0), 0);
  const materialSummary = summarizeMaterialUsage(job.materialUsages || []);

  return (
    <Card>
      <BlockStack gap="400">
        <InlineStack align="space-between" blockAlign="start">
          <InlineStack gap="300" blockAlign="start">
            {firstImage ? (
              <img src={firstImage} alt="Product" style={{ width: 96, height: 96, objectFit: "cover", borderRadius: 12, border: "1px solid #ddd" }} />
            ) : (
              <div style={{ width: 96, height: 96, borderRadius: 12, border: "1px dashed #bbb", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12 }}>
                No image
              </div>
            )}
            <BlockStack gap="100">
              <Text as="h3" variant="headingMd">{job.company || job.customerName || "Production Job"}</Text>
              <Text as="p" tone="subdued">Ticket {job.jobTicket || job.id} | Quote {job.quoteId || "N/A"}</Text>
              <Text as="p" tone="subdued">Recommended folder: {folderNameForJob(job)}</Text>
              <InlineStack gap="200">
                <Badge tone="success">{labelForStatus(job.status)}</Badge>
                <Badge>{job.jobTicket || "No ticket"}</Badge>
                <Badge>{job.priority}</Badge>
                {job.dueDate ? <Badge>Due {new Date(job.dueDate).toLocaleDateString()}</Badge> : null}
              </InlineStack>
              <InlineStack gap="150" wrap>
                <Button onClick={() => copyText(job.jobTicket || job.id)}>Copy Job Ticket</Button>
                <Button onClick={() => copyText(folderNameForJob(job))}>Copy Folder Name</Button>
                <Button onClick={() => copyText(job.items?.[0]?.ripJobName || job.jobTicket || job.id)}>Copy RIP Name</Button>
              </InlineStack>
              <Card>
                <BlockStack gap="150">
                  <InlineStack align="space-between" blockAlign="center">
                    <Text as="h4" variant="headingSm">Customer Proof Approval</Text>
                    <Badge tone={job.proofStatus === "approved" ? "success" : job.proofStatus === "changes_requested" ? "critical" : job.proofApprovalToken ? "attention" : "warning"}>
                      {job.proofStatus ? labelForStatus(job.proofStatus) : job.proofApprovalToken ? "Link Ready" : "No Link"}
                    </Badge>
                  </InlineStack>
                  {job.customerProofUrl ? (
                    <BlockStack gap="100">
                      <Text as="p" tone="subdued">Customer link: {job.customerProofUrl}</Text>
                      <InlineStack gap="150" wrap>
                        <Button onClick={() => copyText(job.customerProofUrl)}>Copy Customer Proof Link</Button>
                        <Button onClick={() => window.open(job.customerProofUrl, "_blank")}>Open Customer Proof</Button>
                        <Form method="post">
                          <input type="hidden" name="intent" value="markProofSent" />
                          <input type="hidden" name="jobId" value={job.id} />
                          <Button submit>Mark Sent</Button>
                        </Form>
                      </InlineStack>
                    </BlockStack>
                  ) : (
                    <Form method="post">
                      <input type="hidden" name="intent" value="createProofPortal" />
                      <input type="hidden" name="jobId" value={job.id} />
                      <Button submit>Create Customer Proof Link</Button>
                    </Form>
                  )}
                  {job.proofApprovedAt ? <Text as="p" tone="success">Approved: {new Date(job.proofApprovedAt).toLocaleString()}</Text> : null}
                  {job.proofCustomerComment ? <Text as="p" tone="subdued">Customer comment: {job.proofCustomerComment}</Text> : null}
                </BlockStack>
              </Card>
            </BlockStack>
          </InlineStack>
          <InlineStack gap="200">
            <Button onClick={() => navigate(`/app/erp/production/${job.id}/proof`)}>Edit Proof</Button>
            <Button onClick={() => navigate(`/app/erp/production/${job.id}/print`)}>Print Work Order</Button>
            <Form method="post">
              <input type="hidden" name="intent" value="markPrinted" />
              <input type="hidden" name="jobId" value={job.id} />
              <Button submit>Mark printed</Button>
            </Form>
          </InlineStack>
        </InlineStack>

        <InlineStack gap="300" wrap>
          <Text as="p">Revenue: ${money(totalRevenue)}</Text>
          <Text as="p">Cost: ${money(totalCost)}</Text>
          <Text as="p">Profit: ${money(totalRevenue - totalCost)}</Text>
          <Text as="p">Assigned: {job.assignedTo || "Unassigned"}</Text>
        </InlineStack>

        <Card>
          <BlockStack gap="200">
            <InlineStack align="space-between" blockAlign="center">
              <Text as="h4" variant="headingSm">Actual Cost Summary</Text>
              {Number(job.actuals?.entryCount || 0) > 0 ? <Badge tone="success">{job.actuals.entryCount} print log(s)</Badge> : <Badge tone="warning">No print logs matched</Badge>}
            </InlineStack>
            {Number(job.actuals?.entryCount || 0) > 0 ? (
              <BlockStack gap="150">
                <InlineStack gap="300" wrap>
                  <Text as="p">Actual sqft: {Number(job.actuals.actualSqft || 0).toFixed(2)}</Text>
                  <Text as="p">Ink: {Number(job.actuals.actualInkMl || 0).toFixed(2)} ml</Text>
                  <Text as="p">Print time: {Number(job.actuals.actualPrintMinutes || 0).toFixed(2)} min</Text>
                  <Text as="p">Rough print cost: ${money(job.actuals.roughActualPrintCost)}</Text>
                  <Text as="p">Actual material cost: ${money(materialSummary.materialCost)}</Text>
                </InlineStack>
                <InlineStack gap="300" wrap>
                  <Text as="p">CMYK: {Number(job.actuals.cmykInkMl || 0).toFixed(2)} ml</Text>
                  <Text as="p">White: {Number(job.actuals.whiteInkMl || 0).toFixed(2)} ml</Text>
                  <Text as="p">Gloss: {Number(job.actuals.glossInkMl || 0).toFixed(2)} ml</Text>
                  <Text as="p">Profit after logged print + material cost: ${money(job.actuals.conservativeProfitAfterLoggedPrintCost - materialSummary.materialCost)}</Text>
                </InlineStack>
                <Text as="p" tone="subdued">
                  Print cost preview uses the shared verified channel-cost engine and the configured ${job.actuals.machineRatePerHour}/hr machine rate
                  (same engine as Audit · Actual Costs). {job.actuals.inkRatesCovered ? "" : "Some rows lack attributable ink rates and are excluded from the ink preview. "}
                  {Number(job.actuals.cutRowCount || 0) > 0 ? `${job.actuals.cutRowCount} cut row(s) are excluded from ink/time cost. ` : ""}
                </Text>

                {/* 13A.7B: guarded print-log writeback (preview -> typed phrase -> apply) */}
                <Card>
                  <BlockStack gap="150">
                    <InlineStack align="space-between" blockAlign="center">
                      <Text as="h4" variant="headingSm">Pull actuals from print logs</Text>
                      {job.printLogApplied ? <Badge tone="success">{`Imported $${money(job.printLogApplied.totalCost)}`}</Badge> : <Badge tone="attention">Not imported yet</Badge>}
                    </InlineStack>
                    {job.printLogApplied ? (
                      <Text as="p" tone="subdued">
                        Applied {job.printLogApplied.appliedAt ? new Date(job.printLogApplied.appliedAt).toLocaleString() : "(time unknown)"}
                        {job.printLogApplied.appliedBy ? ` by ${job.printLogApplied.appliedBy}` : ""}:{" "}
                        {job.printLogApplied.components.map((component: any) => `${component.name} $${money(component.totalCost)} (${component.usedQty.toFixed(2)} ${component.unit})`).join(" + ")}.
                        Material excluded. PARTIAL — job is not finalized. Re-apply below when new logs arrive (replaces only these imported rows).
                      </Text>
                    ) : null}
                    {job.writebackPreview?.ok ? (
                      <BlockStack gap="100">
                        <Text as="p">
                          Proposed writeback: <b>${money(job.writebackPreview.totalCost)}</b> = ink {job.writebackPreview.inkCost == null ? "n/a" : `$${money(job.writebackPreview.inkCost)} (${job.writebackPreview.inkMl.toFixed(2)} ml)`}
                          {" + "}machine {job.writebackPreview.machineCost == null ? "n/a" : `$${money(job.writebackPreview.machineCost)} (${job.writebackPreview.printMinutes.toFixed(1)} min @ $${job.writebackPreview.machineRatePerHour}/hr)`}
                        </Text>
                        <Text as="p" tone="subdued">
                          {job.writebackPreview.printRowCount} print row(s){job.writebackPreview.cutRowsExcluded ? `, ${job.writebackPreview.cutRowsExcluded} cut excluded` : ""}
                          {job.writebackPreview.duplicatesIgnored ? `, ${job.writebackPreview.duplicatesIgnored} duplicate(s) ignored` : ""}
                          {" · runs: "}{job.writebackPreview.runCount == null ? "unknown" : job.writebackPreview.runCount}{job.writebackPreview.reprintDetected ? " (reprints included)" : ""}
                          {" · match: "}{job.writebackPreview.matchMethods.join(", ")} · {job.writebackPreview.printers.join(", ")}
                          {job.writebackPreview.itemTicketAttribution ? ` · item ${job.writebackPreview.itemTicketAttribution}` : ""}
                          {" · material preview-only (not written)"}
                        </Text>
                        {(job.writebackPreview.warnings || []).slice(0, 6).map((warning: string) => (
                          <Text as="p" tone="subdued" key={warning}>⚠ {warning}</Text>
                        ))}
                        <Form method="post">
                          <input type="hidden" name="intent" value="pullPrintLogActuals" />
                          <input type="hidden" name="jobId" value={job.id} />
                          <InlineStack gap="200" blockAlign="center" wrap>
                            <input
                              name="confirmPhrase"
                              placeholder='Type APPLY PRINT LOG ACTUALS'
                              autoComplete="off"
                              style={{ padding: 8, borderRadius: 8, border: "1px solid #aaa", minWidth: 260 }}
                            />
                            <Button submit variant="primary">{job.printLogApplied ? "Re-apply print-log actuals" : "Apply print-log actuals"}</Button>
                            <Button onClick={() => navigate("/app/erp/actual-costs")}>Audit · Actual Costs</Button>
                          </InlineStack>
                        </Form>
                      </BlockStack>
                    ) : (
                      <Text as="p" tone="subdued">Writeback unavailable: {job.writebackPreview?.blockedReason || "no preview computed"}</Text>
                    )}
                  </BlockStack>
                </Card>
              </BlockStack>
            ) : (
              <Text as="p" tone="subdued">Import a VersaWorks/RasterLink log using the job or item ticket to fill actual sqft, ink, time, and rough print cost.</Text>
            )}
          </BlockStack>
        </Card>

        <Card>
          <BlockStack gap="250">
            <InlineStack align="space-between" blockAlign="center">
              <Text as="h4" variant="headingSm">Final Actual Cost</Text>
              {job.actualCostFinalized ? <Badge tone="success">Finalized</Badge> : <Badge tone="warning">Open</Badge>}
            </InlineStack>
            <InlineStack gap="300" wrap>
              <Text as="p">Revenue: ${money(summarizeFinalActualCosts(job, job.actuals, materialSummary).revenue)}</Text>
              <Text as="p">Final cost: ${money(summarizeFinalActualCosts(job, job.actuals, materialSummary).finalTotal)}</Text>
              <Text as="p">Final profit: ${money(summarizeFinalActualCosts(job, job.actuals, materialSummary).finalProfit)}</Text>
              <Text as="p">Final margin: {Number(summarizeFinalActualCosts(job, job.actuals, materialSummary).finalMargin || 0).toFixed(1)}%</Text>
              <Text as="p">Variance vs estimate: ${money(summarizeFinalActualCosts(job, job.actuals, materialSummary).estimateVariance)}</Text>
            </InlineStack>
            <Text as="p" tone="subdued">Use this to close the job after production. Print/material costs come from logs and material usage; add labor, packing, shipping, outsource invoices, reprints, and other costs here.</Text>
            <Form method="post">
              <input type="hidden" name="intent" value="saveFinalCosts" />
              <input type="hidden" name="jobId" value={job.id} />
              <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(160px, 1fr))", gap: 12 }}>
                <label>Labor minutes<input name="actualLaborMinutes" type="number" step="0.01" defaultValue={job.actualLaborMinutes || ""} style={{ width: "100%", padding: 8 }} /></label>
                <label>Labor rate/hr<input name="actualLaborRate" type="number" step="0.01" defaultValue={job.actualLaborRate || 25} style={{ width: "100%", padding: 8 }} /></label>
                <label>Labor cost override<input name="actualLaborCost" type="number" step="0.01" defaultValue={job.actualLaborCost || ""} style={{ width: "100%", padding: 8 }} /></label>
                <label>Packing cost<input name="actualPackingCost" type="number" step="0.01" defaultValue={job.actualPackingCost || ""} style={{ width: "100%", padding: 8 }} /></label>
                <label>Shipping cost<input name="actualShippingCost" type="number" step="0.01" defaultValue={job.actualShippingCost || ""} style={{ width: "100%", padding: 8 }} /></label>
                <label>Outsource invoice cost<input name="actualOutsourceCost" type="number" step="0.01" defaultValue={job.actualOutsourceCost || ""} style={{ width: "100%", padding: 8 }} /></label>
                <label>Reprint cost<input name="actualReprintCost" type="number" step="0.01" defaultValue={job.actualReprintCost || ""} style={{ width: "100%", padding: 8 }} /></label>
                <label>Other cost<input name="actualOtherCost" type="number" step="0.01" defaultValue={job.actualOtherCost || ""} style={{ width: "100%", padding: 8 }} /></label>
                <label>Finalize job cost<select name="actualCostFinalized" defaultValue={job.actualCostFinalized ? "true" : "false"} style={{ width: "100%", padding: 8 }}><option value="false">No</option><option value="true">Yes - lock final cost</option></select></label>
              </div>
              <label style={{ display: "block", marginTop: 12 }}>Final cost notes<textarea name="actualCostNotes" defaultValue={job.actualCostNotes || ""} rows={3} style={{ width: "100%", padding: 8 }} /></label>
              <Button submit>{job.actualCostFinalized ? "Update finalized cost" : "Save final cost"}</Button>
            </Form>
            {job.actualCostFinalizedAt ? <Text as="p" tone="success">Finalized: {new Date(job.actualCostFinalizedAt).toLocaleString()}</Text> : null}
          </BlockStack>
        </Card>

        <Card>
          <BlockStack gap="250">
            <InlineStack align="space-between" blockAlign="center">
              <Text as="h4" variant="headingSm">Material Usage + Waste</Text>
              {(job.materialUsages || []).length ? <Badge tone="success">{job.materialUsages.length} material row(s)</Badge> : <Badge tone="warning">No material logged</Badge>}
            </InlineStack>
            <InlineStack gap="300" wrap>
              <Text as="p">Material cost: ${money(materialSummary.materialCost)}</Text>
              <Text as="p">Pulled: {Number(materialSummary.pulledQty || 0).toFixed(2)}</Text>
              <Text as="p">Used: {Number(materialSummary.usedQty || 0).toFixed(2)}</Text>
              <Text as="p">Waste: {Number(materialSummary.wasteQty || 0).toFixed(2)}</Text>
              <Text as="p">Reprint: {Number(materialSummary.reprintQty || 0).toFixed(2)}</Text>
              <Text as="p">Deducted from stock: {Number(materialSummary.deductedQty || 0).toFixed(2)}</Text>
              <Text as="p">Waste %: {Number(materialSummary.wastePct || 0).toFixed(1)}%</Text>
            </InlineStack>

            {(job.materialUsages || []).length ? (
              <BlockStack gap="150">
                {(job.materialUsages || []).map((usage: any) => (
                  <Card key={usage.id}>
                    <InlineStack align="space-between" blockAlign="center" gap="200">
                      <BlockStack gap="050">
                        <Text as="p" fontWeight="bold">{usage.materialName}</Text>
                        <Text as="p" tone="subdued">
                          {materialTypeLabel(usage.materialType)} | Used {Number(usage.usedQty || usage.pulledQty || usage.estimatedQty || 0).toFixed(2)} {usage.unit} | Waste {Number(usage.wasteQty || 0).toFixed(2)} | Deducted {Number(usage.stockDeductedQty || 0).toFixed(2)} | Cost ${money(usage.totalCost)}
                        </Text>
                        {usage.notes ? <Text as="p" tone="subdued">{usage.notes}</Text> : null}
                      </BlockStack>
                      <Form method="post">
                        <input type="hidden" name="intent" value="deleteMaterialUsage" />
                        <input type="hidden" name="jobId" value={job.id} />
                        <input type="hidden" name="usageId" value={usage.id} />
                        <Button submit tone="critical">Remove</Button>
                      </Form>
                    </InlineStack>
                  </Card>
                ))}
              </BlockStack>
            ) : (
              <Text as="p" tone="subdued">Track roll media, laminate, packaging, reprints, and waste here. This moves the job from estimated cost toward true production cost.</Text>
            )}

            <Form method="post">
              <input type="hidden" name="intent" value="addMaterialUsage" />
              <input type="hidden" name="jobId" value={job.id} />
              <BlockStack gap="200">
                <InlineStack gap="200" wrap>
                  <div style={{ minWidth: 260, flex: 1 }}>
                    <label style={{ display: "block", fontWeight: 600, marginBottom: 4 }}>Material from database</label>
                    <select name="materialId" defaultValue="" style={{ width: "100%", padding: 8, borderRadius: 8, border: "1px solid #bbb" }}>
                      {materialOptions(materials).map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}
                    </select>
                  </div>
                  <TextField label="Manual material name" name="materialName" autoComplete="off" placeholder="Only needed if not choosing database material" />
                  <div style={{ minWidth: 160 }}>
                    <label style={{ display: "block", fontWeight: 600, marginBottom: 4 }}>Type</label>
                    <select name="materialType" defaultValue="roll_media" style={{ width: "100%", padding: 8, borderRadius: 8, border: "1px solid #bbb" }}>
                      <option value="roll_media">Roll media</option>
                      <option value="laminate">Laminate</option>
                      <option value="packaging">Packaging</option>
                      <option value="ink">Ink</option>
                      <option value="labor">Labor</option>
                      <option value="outsourced">Outsourced</option>
                      <option value="other">Other</option>
                    </select>
                  </div>
                  <TextField label="Unit" name="unit" defaultValue="sqft" autoComplete="off" />
                </InlineStack>
                <InlineStack gap="200" wrap>
                  <TextField label="Estimated qty" name="estimatedQty" type="number" autoComplete="off" />
                  <TextField label="Pulled qty" name="pulledQty" type="number" autoComplete="off" />
                  <TextField label="Used qty" name="usedQty" type="number" autoComplete="off" />
                  <TextField label="Waste qty" name="wasteQty" type="number" autoComplete="off" />
                  <TextField label="Reprint qty" name="reprintQty" type="number" autoComplete="off" />
                  <TextField label="Cost / unit" name="costPerUnit" type="number" autoComplete="off" />
                  <TextField label="Override total cost" name="totalCost" type="number" autoComplete="off" />
                </InlineStack>
                <InlineStack gap="200" wrap>
                  <div style={{ minWidth: 180 }}>
                    <label style={{ display: "block", fontWeight: 600, marginBottom: 4 }}>Source</label>
                    <select name="source" defaultValue="manual" style={{ width: "100%", padding: 8, borderRadius: 8, border: "1px solid #bbb" }}>
                      <option value="manual">Manual</option>
                      <option value="recipe">Recipe estimate</option>
                      <option value="print_log">Print log</option>
                      <option value="inventory">Inventory pull</option>
                      <option value="vendor_invoice">Vendor invoice</option>
                    </select>
                  </div>
                  <TextField label="Deduct qty override" name="deductQty" type="number" autoComplete="off" placeholder="Optional" />
                  <label style={{ display: "flex", gap: 8, alignItems: "center", marginTop: 22 }}>
                    <input type="checkbox" name="deductInventory" />
                    Deduct from material stock
                  </label>
                  <TextField label="Notes" name="materialNotes" autoComplete="off" />
                </InlineStack>
                <Text as="p" tone="subdued">Inventory deduction only works when a database material is selected. Deducted qty uses pulled qty first, then used + waste + reprint.</Text>
                <Button submit>Add material usage</Button>
              </BlockStack>
            </Form>
          </BlockStack>
        </Card>

        <Card>
          <BlockStack gap="250">
            <InlineStack align="space-between" blockAlign="center">
              <Text as="h4" variant="headingSm">Inventory Snapshot</Text>
              <Badge>{materials.length} active material(s)</Badge>
            </InlineStack>
            <Text as="p" tone="subdued">Use this to make quick stock adjustments while checking production jobs. Positive qty adds stock, negative qty removes stock.</Text>
            <InlineStack gap="200" wrap>
              {materials.slice(0, 8).map((material: any) => (
                <Badge key={material.id} tone={materialStockTone(material) as any}>{material.name}: {material.stockOnHand == null ? "stock not set" : Number(material.stockOnHand).toFixed(2)} {material.baseUnit || material.unit}</Badge>
              ))}
            </InlineStack>
            <Form method="post">
              <input type="hidden" name="intent" value="adjustInventory" />
              <input type="hidden" name="jobId" value={job.id} />
              <InlineStack gap="200" wrap>
                <div style={{ minWidth: 260, flex: 1 }}>
                  <label style={{ display: "block", fontWeight: 600, marginBottom: 4 }}>Material</label>
                  <select name="materialId" defaultValue="" style={{ width: "100%", padding: 8, borderRadius: 8, border: "1px solid #bbb" }}>
                    {materialOptions(materials).map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}
                  </select>
                </div>
                <TextField label="Adjustment qty" name="adjustQty" type="number" autoComplete="off" placeholder="ex: 100 or -10" />
                <TextField label="Adjustment notes" name="adjustNotes" autoComplete="off" />
                <Button submit>Adjust stock</Button>
              </InlineStack>
            </Form>
          </BlockStack>
        </Card>

        <Divider />

        <BlockStack gap="200">
          <Text as="h4" variant="headingSm">Items / variants</Text>
          {(job.items || []).map((item: any) => (
            <Card key={item.id}>
              <InlineStack gap="300" blockAlign="start" wrap>
                {item.productImageUrl ? (
                  <img src={item.productImageUrl} alt="Item" style={{ width: 72, height: 72, objectFit: "cover", borderRadius: 10, border: "1px solid #ddd" }} />
                ) : null}
                <BlockStack gap="050">
                  <Text as="p" fontWeight="bold">{item.productTitle}</Text>
                  <Text as="p" tone="subdued">Variant: {item.variantTitle || "None"} | SKU: {item.sku || "None"}</Text>
                  {(() => {
                    const config = configFromItem(item);
                    return (
                      <BlockStack gap="050">
                        <Text as="p">Qty: {item.quantity} | Unit: ${money(item.unitPrice)} | Total: ${money(lineTotalForItem(item))}</Text>
                        {config.isJar ? (
                          <>
                            <Text as="p">Material: {config.material || "N/A"} | Finish: {config.finish || "N/A"} | Label Set: {config.labelSet || "N/A"}</Text>
                            {config.jarColor ? <Text as="p">Jar Color: {config.jarColor}</Text> : null}
                            <Text as="p">Production Finish: {config.productionFinish || "N/A"}</Text>
                          </>
                        ) : (
                          <>
                            <Text as="p">Material: {config.material || "N/A"} | Finish: {config.finish || "N/A"} | Bag Color: {config.bagColor || "N/A"}</Text>
                            <Text as="p">Production Finish: {config.productionFinish || "N/A"} | Sides: {config.sides || "N/A"}</Text>
                          </>
                        )}
                      </BlockStack>
                    );
                  })()}
                  {item.recipeName ? <Text as="p" tone="subdued">Recipe: {item.recipeName}</Text> : null}
                  <Text as="p" tone="subdued">Item ticket: {item.itemTicket || "Not assigned yet"}</Text>
                  <Text as="p" tone="subdued">Print file name: {item.suggestedFileName || "Not assigned yet"}</Text>
                  <InlineStack gap="150" wrap>
                    <Button onClick={() => copyText(item.itemTicket || "")}>Copy Item Ticket</Button>
                    <Button onClick={() => copyText(item.ripJobName || item.itemTicket || "")}>Copy RIP Job Name</Button>
                    <Button onClick={() => copyText(item.suggestedFileName || "")}>Copy Print File Name</Button>
                  </InlineStack>
                </BlockStack>
              </InlineStack>
            </Card>
          ))}
        </BlockStack>

        <InlineStack gap="300" wrap>
          <div style={{ minWidth: 260, flex: 1 }}>
            <Form method="post">
              <input type="hidden" name="intent" value="changeStatus" />
              <input type="hidden" name="jobId" value={job.id} />
              <label style={{ display: "block", fontWeight: 600, marginBottom: 4 }}>Move job to</label>
              <select name="status" defaultValue={job.status} style={{ width: "100%", padding: 8, borderRadius: 8, border: "1px solid #bbb" }}>
                {productionStatuses.map((status) => <option key={status.value} value={status.value}>{status.label}</option>)}
              </select>
              <Button submit>Update status</Button>
            </Form>
          </div>

          <div style={{ minWidth: 320, flex: 2 }}>
            <Form method="post">
              <input type="hidden" name="intent" value="updateJob" />
              <input type="hidden" name="jobId" value={job.id} />
              <BlockStack gap="200">
                <InlineStack gap="200">
                  <div style={{ minWidth: 160 }}>
                    <label style={{ display: "block", fontWeight: 600, marginBottom: 4 }}>Priority</label>
                    <select name="priority" defaultValue={job.priority || "normal"} style={{ width: "100%", padding: 8, borderRadius: 8, border: "1px solid #bbb" }}>
                      {priorityOptions.map((priority) => <option key={priority.value} value={priority.value}>{priority.label}</option>)}
                    </select>
                  </div>
                  <TextField label="Due date" name="dueDate" type="date" defaultValue={safeDateInput(job.dueDate)} autoComplete="off" />
                  <TextField label="Assigned to" name="assignedTo" defaultValue={job.assignedTo || ""} autoComplete="off" />
                </InlineStack>
                <TextField label="Job ticket" name="assetInboxKey" defaultValue={job.assetInboxKey || job.jobTicket || ""} autoComplete="off" helpText="Use this exact ticket in Google Drive folders, VersaWorks, RasterLink, and print file names." />
                <TextField label="Drive / asset folder URL" name="assetFolderUrl" defaultValue={job.assetFolderUrl || ""} autoComplete="off" />
                <TextField label="Source folder URL / customer upload folder" name="sourceFolderUrl" defaultValue={job.sourceFolderUrl || ""} autoComplete="off" />
                <TextField label="Product image URL" name="productImageUrl" defaultValue={job.productImageUrl || ""} autoComplete="off" />
                <TextField label="Artwork URL" name="artworkUrl" defaultValue={job.artworkUrl || ""} autoComplete="off" />
                <TextField label="Proof URL" name="proofUrl" defaultValue={job.proofUrl || ""} autoComplete="off" />
                <TextField label="Print file URL" name="printFileUrl" defaultValue={job.printFileUrl || ""} autoComplete="off" />
                <TextField label="Internal notes" name="internalNotes" defaultValue={job.internalNotes || ""} multiline={3} autoComplete="off" />
                <TextField label="Customer notes" name="customerNotes" defaultValue={job.customerNotes || ""} multiline={2} autoComplete="off" />
                <Button submit>Save job details</Button>
              </BlockStack>
            </Form>
          </div>
        </InlineStack>

        <InlineStack gap="300" align="start" wrap>
          <div style={{ minWidth: 280, flex: 1 }}>
            <Card>
              <BlockStack gap="200">
                <Text as="h4" variant="headingSm">Checklist</Text>
                {(job.checklistItems || []).map((check: any) => (
                  <Form method="post" key={check.id}>
                    <input type="hidden" name="intent" value="toggleChecklist" />
                    <input type="hidden" name="jobId" value={job.id} />
                    <input type="hidden" name="checklistId" value={check.id} />
                    <input type="hidden" name="completed" value={check.completed ? "false" : "true"} />
                    <Checkbox label={`${check.section}: ${check.label}`} checked={check.completed} onChange={() => {}} />
                    <Button submit>{check.completed ? "Undo" : "Complete"}</Button>
                  </Form>
                ))}
              </BlockStack>
            </Card>
          </div>

          <div style={{ minWidth: 360, flex: 1 }}>
            <Card>
              <BlockStack gap="300">
                <InlineStack align="space-between" blockAlign="center">
                  <Text as="h4" variant="headingSm">Asset Manager</Text>
                  <Badge>{(job.files || []).length} file(s)</Badge>
                </InlineStack>

                <BlockStack gap="100">
                  <Text as="p" tone="subdued">Job ticket: {job.jobTicket || "Not assigned"}</Text>
                  <Text as="p" tone="subdued">Drive folder: {job.assetFolderUrl ? "Linked" : "Not linked"}</Text>
                  <Text as="p" tone="subdued">Source folder: {job.sourceFolderUrl ? "Linked" : "Not linked"}</Text>
                  <Text as="p" tone="subdued">Main product image: {job.productImageUrl ? "Linked" : "Not linked"}</Text>
                  <Text as="p" tone="subdued">Main artwork: {job.artworkUrl ? "Linked" : "Not linked"}</Text>
                  <Text as="p" tone="subdued">Current proof: {job.proofUrl ? "Linked" : "Not linked"}</Text>
                  <Text as="p" tone="subdued">Print file: {job.printFileUrl ? "Linked" : "Not linked"}</Text>
                </BlockStack>

                {(job.files || []).length ? (job.files || []).map((file: any) => (
                  <Card key={file.id}>
                    <BlockStack gap="200">
                      <InlineStack align="space-between" blockAlign="start">
                        <BlockStack gap="050">
                          <Text as="p" fontWeight="bold"><a href={file.fileUrl} target="_blank" rel="noreferrer">{file.fileName}</a></Text>
                          <Text as="p" tone="subdued">{file.fileType} | {assetRoleLabel(file.assetRole || "reference")} | {sourceLabel(file.assetSource || "manual")} | {new Date(file.createdAt).toLocaleString()}</Text>
                          {file.sourceRef ? <Text as="p" tone="subdued">Source ref: {file.sourceRef}</Text> : null}
                        </BlockStack>
                        <Badge>{file.fileType}</Badge>
                      </InlineStack>

                      {isImageUrl(file.fileUrl) ? (
                        <img src={file.fileUrl} alt={file.fileName} style={{ width: "100%", maxHeight: 180, objectFit: "contain", border: "1px solid #ddd", borderRadius: 10, background: "#fafafa" }} />
                      ) : isPdfUrl(file.fileUrl) ? (
                        <div style={{ padding: 12, border: "1px solid #ddd", borderRadius: 10, background: "#fafafa" }}>
                          <Text as="p">PDF attached. Open the link to view or print.</Text>
                        </div>
                      ) : null}

                      {file.notes ? <Text as="p" tone="subdued">{file.notes}</Text> : null}

                      <InlineStack gap="150" wrap>
                        {["productImage", "artwork", "proof", "printFile"].map((role) => (
                          <Form method="post" key={`${file.id}-${role}`}>
                            <input type="hidden" name="intent" value="setFileRole" />
                            <input type="hidden" name="jobId" value={job.id} />
                            <input type="hidden" name="fileId" value={file.id} />
                            <input type="hidden" name="assetRole" value={role} />
                            <Button submit>{assetRoleLabel(role)}</Button>
                          </Form>
                        ))}
                        <Form method="post">
                          <input type="hidden" name="intent" value="deleteFile" />
                          <input type="hidden" name="jobId" value={job.id} />
                          <input type="hidden" name="fileId" value={file.id} />
                          <Button submit tone="critical">Remove</Button>
                        </Form>
                      </InlineStack>
                    </BlockStack>
                  </Card>
                )) : <Text as="p" tone="subdued">No assets linked yet. Add artwork, PDF, proof, image, dieline, or print file URLs below.</Text>}

                <Form method="post">
                  <input type="hidden" name="intent" value="addFile" />
                  <input type="hidden" name="jobId" value={job.id} />
                  <BlockStack gap="150">
                    <TextField label="File name" name="fileName" autoComplete="off" />
                    <InlineStack gap="200">
                      <div style={{ flex: 1 }}>
                        <label style={{ display: "block", fontWeight: 600, marginBottom: 4 }}>File type</label>
                        <select name="fileType" defaultValue="artwork" style={{ width: "100%", padding: 8, borderRadius: 8, border: "1px solid #bbb" }}>
                          {fileTypeOptions.map((fileType) => <option key={fileType.value} value={fileType.value}>{fileType.label}</option>)}
                        </select>
                      </div>
                      <div style={{ flex: 1 }}>
                        <label style={{ display: "block", fontWeight: 600, marginBottom: 4 }}>Source</label>
                        <select name="assetSource" defaultValue="google_drive" style={{ width: "100%", padding: 8, borderRadius: 8, border: "1px solid #bbb" }}>
                          {assetSourceOptions.map((source) => <option key={source.value} value={source.value}>{source.label}</option>)}
                        </select>
                      </div>
                      <div style={{ flex: 1 }}>
                        <label style={{ display: "block", fontWeight: 600, marginBottom: 4 }}>Use as</label>
                        <select name="assetRole" defaultValue="artwork" style={{ width: "100%", padding: 8, borderRadius: 8, border: "1px solid #bbb" }}>
                          <option value="reference">Reference only</option>
                          <option value="productImage">Product image</option>
                          <option value="artwork">Main artwork</option>
                          <option value="proof">Current proof</option>
                          <option value="printFile">Print file</option>
                        </select>
                      </div>
                    </InlineStack>
                    <TextField label="File URL / PDF / artwork link" name="fileUrl" autoComplete="off" helpText="Paste a Shopify Files, Google Drive, Dropbox, Cloudinary, S3, or public artwork link." />
                    <TextField label="Source reference optional" name="sourceRef" autoComplete="off" helpText="Example: email subject, Zakeke design ID, Google Drive file ID, VersaWorks job name, RasterLink job name." />
                    <TextField label="Notes" name="fileNotes" autoComplete="off" />
                    <Button submit variant="primary">Add asset link</Button>
                  </BlockStack>
                </Form>
              </BlockStack>
            </Card>
          </div>

          <div style={{ minWidth: 320, flex: 1 }}>
            <Card>
              <BlockStack gap="200">
                <Text as="h4" variant="headingSm">Event log / notes</Text>
                <Form method="post">
                  <input type="hidden" name="intent" value="addNote" />
                  <input type="hidden" name="jobId" value={job.id} />
                  <TextField label="Add production note" name="note" autoComplete="off" />
                  <Button submit>Add note</Button>
                </Form>
                {(job.events || []).map((event: any) => (
                  <Text as="p" key={event.id} tone="subdued">{new Date(event.createdAt).toLocaleString()}: {event.message}</Text>
                ))}
              </BlockStack>
            </Card>
          </div>
        </InlineStack>
      </BlockStack>
    </Card>
  );
}

export default function ProductionBoard() {
  const { jobs, quotes, materials } = useLoaderData<any>();
  const actionData = useActionData<any>();
  const navigation = useNavigation();
  const busy = navigation.state !== "idle";

  const quoteOptions = [
    { label: "Choose approved / paid quote", value: "" },
    ...quotes.map((quote: any) => ({
      label: `${quote.company || quote.customerName || quote.email || quote.id} | ${quote.status} | ${quote.items?.length || 0} item(s)`,
      value: quote.id,
    })),
  ];

  const statusGroups = productionStatuses
    .map((status) => ({ ...status, jobs: jobs.filter((job: any) => job.status === status.value) }))
    .filter((group) => group.jobs.length || ["new", "prepress", "printing", "qc", "completed"].includes(group.value));

  return (
    <Page title="Production Board" subtitle="Create production jobs from approved/paid quotes, track stages, files, variants, notes, alerts, and printable work orders.">
      <Layout>
        <Layout.Section>
          <Card>
            <BlockStack gap="300">
              <InlineStack align="space-between" blockAlign="center">
                <BlockStack gap="100">
                  <Text as="h2" variant="headingMd">Create production job</Text>
                  <Text as="p" tone="subdued">Production jobs snapshot quote items, variants, quantities, images, recipes, file links, and pricing/cost data.</Text>
                </BlockStack>
                <InlineStack gap="200">
                  <Badge tone="success">{jobs.length} active job(s)</Badge>
                  <Form method="post">
                    <input type="hidden" name="intent" value="backfillTickets" />
                    <Button submit>Backfill tickets</Button>
                  </Form>
                </InlineStack>
              </InlineStack>
              {actionData?.message ? <Text as="p" tone={actionData.ok ? "success" : "critical"}>{actionData.message}</Text> : null}
              <Form method="post">
                <input type="hidden" name="intent" value="createFromQuote" />
                <InlineStack gap="300" blockAlign="end">
                  <div style={{ minWidth: 360, flex: 1 }}>
                    <label style={{ display: "block", fontWeight: 600, marginBottom: 4 }}>Approved / paid quote</label>
                    <select name="quoteId" defaultValue="" style={{ width: "100%", padding: 8, borderRadius: 8, border: "1px solid #bbb" }}>
                      {quoteOptions.map((quote) => <option key={quote.value} value={quote.value}>{quote.label}</option>)}
                    </select>
                  </div>
                  <Button submit variant="primary" loading={busy}>Create from quote</Button>
                </InlineStack>
              </Form>
              <Text as="p" tone="subdued">Slack alerts are sent automatically if SLACK_WEBHOOK_URL or PRODUCTION_SLACK_WEBHOOK_URL is set in Render.</Text>
            </BlockStack>
          </Card>
        </Layout.Section>

        {statusGroups.map((group) => (
          <Layout.Section key={group.value}>
            <BlockStack gap="300">
              <InlineStack align="space-between" blockAlign="center">
                <Text as="h2" variant="headingMd">{group.label}</Text>
                <Badge>{group.jobs.length}</Badge>
              </InlineStack>
              {group.jobs.length ? group.jobs.map((job: any) => <JobCard key={job.id} job={job} materials={materials || []} />) : <Card><Text as="p" tone="subdued">No jobs in this stage.</Text></Card>}
            </BlockStack>
          </Layout.Section>
        ))}
      </Layout>
    </Page>
  );
}
