api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "gso-wholesale-discount"
type = "function"
uid = "cdfcd1b0-9607-a481-e46c-7d8c4356cc8a0c94e7fa"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart-delivery-options-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
