query CartTransformRunInput {
  cart {
    lines {
      id
      quantity

      gsoConfigurator: attribute(key: "_gso_configurator") {
        key
        value
      }

      gsoErpPriceEach: attribute(key: "_GSO ERP Price Each") {
        key
        value
      }

      gsoErpMatchedTier: attribute(key: "_GSO ERP Matched Tier") {
        key
        value
      }

      material: attribute(key: "Material") {
        key
        value
      }

      finish: attribute(key: "Finish") {
        key
        value
      }

      bagColor: attribute(key: "Bag Color") {
        key
        value
      }

      sides: attribute(key: "Sides") {
        key
        value
      }

      merchandise {
        ... on ProductVariant {
          id
          title
          product {
            title
          }
        }
      }
    }
  }
}
